/**
 * Enumeration for parsing the numbers in the definition of a route map.
 */
export enum RouteMapHold {
  HexaGreenIn,
  HexaYellowIn,
  HexaOrangeIn,
  HexaBlueIn,
  HexaPinkIn,
  HexaGrayIn,
  HexaWhiteIn,
  HexaBrownIn,
  HexaDarkblueIn,
  HexaDarkgreenIn,

  HexaGreenOut,
  HexaYellowOut,
  HexaOrangeOut,
  HexaBlueOut,
  HexaPinkOut,
  HexaGrayOut,
  HexaWhiteOut,
  HexaBrownOut,
  HexaDarkblueOut,
  HexaDarkgreenOut,

  PentaGreenIn,
  PentaYellowIn,
  PentaOrangeIn,
  PentaBlueIn,
  PentaPinkIn,
  PentaGrayIn,

  PentaGreenOut,
  PentaYellowOut,
  PentaOrangeOut,
  PentaBlueOut,
  PentaPinkOut,
  PentaGrayOut,

  HexaGreenPinch,
  HexaYellowPinch,
  HexaOrangePinch,
  HexaBluePinch,
  HexaPinkPinch,
  HexaGrayPinch,
  HexaWhitePinch,
  HexaBrownPinch,
  HexaDarkbluePinch,
  HexaDarkgreenPinch,

  HexaGreenCrack,
  HexaYellowCrack,
  HexaOrangeCrack,
  HexaBlueCrack,
  HexaPinkCrack,
  HexaGrayCrack,
  HexaWhiteCrack,
  HexaBrownCrack,
  HexaDarkblueCrack,
  HexaDarkgreenCrack,

  Dyno,
}
